CUDA_VISIBLE_DEVICES: 5,

data_process:
  patch_size: 48
  stride: 6



data_set: 
  path: /home/lwt/data_pro/vessel
  name: DRIVE

########### data_loader: #############
batch_size: 256

model:
  type: FRNet
  args: {}

loss:
  type: BCELoss
  args: {}

optimizer:
  type: Adam
  args:
    lr: 1e-4
    weight_decay: 1e-5

lr_scheduler:

  type: CosineAnnealingLR
  args:
    T_max: 40


###########   trainer: ##############
epochs: 40
save_dir: saved/
save_period: 5
log_dir: saved/runs
threshold: 0.5
threshold_low: 0.4
DTI: false
amp: true